
const env = import.meta.env
export const VITE_SUPABASE_URL = env.VITE_SUPABASE_URL
export const VITE_SUPABASE_ANON = env.VITE_SUPABASE_ANON
export const VITE_GOOGLE_CALENDAR_CLIENT_ID = env.VITE_GOOGLE_CALENDAR_CLIENT_ID
export const VITE_GOOGLE_CALENDAR_API = env.VITE_GOOGLE_CALENDAR_API